//YYY 
rule "Dignity - BC of CA - PFR $0 for specific payercode for all payers" 
    when 
        $dto : BenefitsResolutionDTO( 
            $insurances: insuranceInfoList != null, 
            encounterInfo.patientType == "Emergency Room", 
            encounterInfo.medicalService == "Urgent Care", 
            customerAbbr in ("dignta") 
        ) 
 
         $insurance: InsuranceInfo( 
             payerCode in ("BCCALFULL"), 
             recoPayerCode == "REC4160", 
             groupNumber == "76417152", 
             memberNumber matches "^AFY.*", 
             planDesc matches "^AFY.*", , 
             $procedures : procedureInfoList != null 
         ) from $insurances 
 
        $proc : ProcedureInfo( 
            procedureCode == "", 
            revenueCode matches "^0*(320|321|322|323|324|325|326|327|328|329)$" 
        ) from $procedures 
 
    then 
        outputCollector.addRuleOutput(ProcedureBenefitOverrideOutput.newOverride() 
            .forProcedure($proc) 
            .withCopay(0.0) 
            .withCoinsurance(0.0) 
            .withDedApplies(false) 
            .onDto($dto) 
            .fromRule(drools.getRule().getName()) 
        ); 
end