//12312
rule "undefined"
    when
        $sri : StcResolutionInput(
            $episode : episode != null,
            episode ["CustomerAbbr"] == "ASD",
            payerId == "ASD",
            recoPayerId == "ASD",
            revCode == 121,
            providerType == "HOSPITAL",
            patientType == "HOSPITAL",
            providerId == "",
            medicalService == "HOSPITAL",
            providerCode == "",
            $benefits : edDalMaps != null
        )

        DalMap(
            this["EPISODE_INSURANCE.MemberNum"] == ""
        )

        DalMap(
            this["SvcTypeCode"] == "30",
            this["BnftInfoCode"] == BenefitTypeCode.ActiveCoverage.code,
            this["PlanCvgeDesc"] == ""
        ) from $benefits

        $benefit : DalMap(
            this["SvcTypeCode"] == "4",
            this["BnftInfoCode"] in (BenefitTypeCode.CoInsurance.code, BenefitTypeCode.Copayment.code),
            this["InNetworkInd"] == "Y",
            this["ALLMSG"] == "",
            this["BnftAmt"] != null || this["BnftPercent"] != null
        ) from $benefits


    then
        $sri.setStc("4");
        $sri.setMessage("ASDAS");
        retract($sri):
end